esptool.py v4.8.1
Serial port /dev/ttyUSB1

A fatal error occurred: Could not open /dev/ttyUSB1, the port is busy or doesn't exist.
([Errno 11] Could not exclusively lock port /dev/ttyUSB1: [Errno 11] Resource temporarily unavailable)

